# Configurações de fonte
font:
  normal:
    family: Hack NF
    style: Bold #Regular
  bold:
    family: Hack NF
    style: Bold
  italic:
    family: Hack NF
    style: Bold #Italic
  bold_italic:
    family: Hack NF
    style: Bold #Bold Italic
size: 18.0

# Outras configurações de exibição
window.opacity: 0.90
background: '#24283b'
foreground: '#33cccc'
cursor:
  style: Beam
  unfocused_hollow: true
cursor_blink: false
draw_bold_text_with_bright_colors: true
scrollback: 997891

# Configurações do tema de cores
colors:
  primary:
    background: '#24283b'
    foreground: '#33cccc'
  normal:
    black: '#707070'
    red: '#f10e38'
    green: '#00ff00'
    yellow: '#ffff00'
    blue: '#0000ff'
    magenta: '#cc66ff'
    cyan: '#33ccff'
    white: '#bac1de'
  bright:
    black: '#414868'
    red: '#f7768e'
    green: '#9ece6a'
    yellow: '#e0af68'
    blue: '#7aa2f7'
    magenta: '#bb9af7'
    cyan: '#7dcfff'
    white: '#c0caf5'

# Configurações do cursor
#cursor:


# Configurações do mouse
mouse:
  hide_when_typing: true

# Configurações da seleção
selection:
  semantic_escape_chars: ':@-./_~?&=%+#'
