#!/bin/bash
##################################
# A nautilus script to open terminal in the current directory
# place in ~/.local/share/nautilus/scripts
##################################
kitty --working-directory="$(echo "$NAUTILUS_SCRIPT_CURRENT_URI" | cut -c 8-)"
