outputMode: active
scale: 1
background:
  red: 0.12
  green: 0.0
  blue: 0.24
  opacity: 1
widget:
  margin:
    margins:
      - 20
      - 20
      - 20
      - 20
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - date:
                        font: ~
                        font_size: 65
                    - clock:
                        font: ~
                        font_size: 100
            - margin:
                margins:
                  - 20
                  - 20
                  - 20
                  - 20
                widget:
                  verticalLayout:
                    - margin:
                        margins:
                          - 0
                          - 0
                          - 0
                          - 8
                        widget:
                          battery:
                            font_size: 30
                            length: 0
                    - margin:
                        margins:
                          - 0
                          - 0
                          - 0
                          - 8
                        widget:
                          backlight:
                            device: intel_backlight
                            font_size: 30
                            length: 0
                    - margin:
                        margins:
                          - 0
                          - 0
                          - 0
                          - 8
                        widget:
                          pulseAudio:
                            font_size: 30
                            length: 0
        - calendar:
            font_primary: ~
            font_secondary: ~
            font_size: 16.0
            sections: 3
fonts:
  mono: JetBrains Mono
  sans: JetBrains Mono
