#!/bin/bash

# User-specific variables should be placed in $HOME/.config/openbox/environment
#

# set main XDG variables
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CURRENT_DESKTOP=OPENBOX
export XDG_SESSION_DESKTOP=openbox
export XDG_MENU_PREFIX=openbox-

# clean DM influence
export DESKTOP_SESSION=openbox
unset GDMSESSION

# for reducing GTK stderr spam
export NO_AT_BRIDGE=1

# fix and sync Qt and GTK theming
export GTK2_RC_FILES="${HOME}/.gtkrc-2.0:${XDG_CONFIG_HOME}/gtk-2.0/gtkrc:/etc/gtk-2.0/gtkrc"
export QT_QPA_PLATFORMTHEME=gtk2
export QT_QPA_PLATFORM=xcb
export QT_STYLE_OVERRIDE=gtk2
export GTK_RC_FILES=~/.config/gtk-3.0/settings.ini

# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# see https://github.com/NixOS/nixpkgs/issues/14966#issuecomment-520083836
mkdir -p "$HOME"/.local/share/keyrings

# Cursor Theme fix for WMs: openbox, i3 and more...
# How to use lxappearance
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources
Cursor_Theme_Fix()
{
while true
    do export cursor_theme=`cat ~/.config/gtk-3.0/settings.ini | sed -n 5p | cut -c 21-333`
       export cursor_size=`cat ~/.config/gtk-3.0/settings.ini | grep gtk-cursor-theme-size= | cut -c 23-25`
       export cursor_theme_old=`cat ~/.Xresources | sed -n 2p | cut -c 16-333`
       export cursor_size_old=`cat ~/.Xresources | sed -n 3p | cut -c 15-333`
       export cursor_theme_fix_origin=`cat ~/.gtkrc-2.0 | sed -n 8p | sed 's/"//' | sed 's/"//' | cut -c 23-333`
       export cursor_theme_fix_replace=`cat ~/.config/gtk-3.0/settings.ini | grep gtk-icon-theme-name= | cut -c 21-333`
       #export cursor_theme_fix_replace=`cat ~/.config/gtk-3.0/settings.ini | sed -n 5p | cut -c 21-333`
       sed -i "s|$cursor_theme_fix_replace|$cursor_theme_fix_origin|g" ~/.config/gtk-3.0/settings.ini
       sed -i "2 s|$cursor_theme_old|$cursor_theme|g" ~/.Xresources
       sed -i "3 s|$cursor_size_old|$cursor_size|g" ~/.Xresources 
       xsetroot -cursor_name left_ptr
       #export XCURSOR_THEME="$cursor_name"
       #export XCURSOR_SIZE="$cursor_size"
       xrdb -merge ~/.Xresources &
       sleep 1.5
done
}

# Restore persistent volume TV
old_vol=`cat ~/.local/bin/tv-default-volume.sh | head -5 | sed -n 5p | cut -c 16-17 | grep -E "[^[:blank:]]"`
sed -i "5 s|$old_vol|12|g" ~/.local/bin/tv-default-volume.sh
~/.local/bin/tv-default-volume.sh &
~/.local/bin/fix_no-at_shutdown_lgtv.sh &
#eval $(atrm $(seq 999); at -f ~/.local/bin/at-lgtv.sh 23:59) &

Battery_Check()
{
while true
    do battery_check=`LANG=c acpi | awk '{ print $6 }'`
    if [ "$battery_check" = remaining ]; then
        notify-send Power Unplugged
    fi
    sleep 16
done
}

Random_Wallpaper()
{
    sleep 1
    feh --bg-fill "$(find "${HOME}"/Imagens/Wallpapers/ -name '*[jJpP][nNpP][gG]' | shuf -n 1)"
    ###nitrogen --set-zoom-fill $(find /home/$USER/Imagens/Wallpapers/ -name '*[jJpP][nNpP][gG]' | shuf -n1)
}
Xrandr()
{
 sleep 2
###~/.screenlayout/normal.sh &
###xrandr --setprovideroutputsource modesetting modesetting &
###xrandr --auto
###xrandr --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --off &
###xrandr --output HDMI-1-0 --off --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal &
xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate inverted \
	--output eDP-1-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
}

# this file is run when calling startx
# default arch init scripts
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
#        [ -x "$f" ] && . "$f"
#    done
#fi

# user init scripts and settings
#[ -r /etc/X11/xinit/.Xmodmap ] && xmodmap /etc/X11/xinit/.Xmodmap
#[ -r ~/.Xmodmap ] && xmodmap ~/.Xmodmap
#[ -r ~/.Xresources ] && xrdb -merge ~/.Xresources
#[ -r ~/.xprofile ] && . ~/.xprofile

systemctl --user mask pipewire pipewire-pulse

#/usr/lib/mate-settings-daemon/mate-settings-daemon &
Random_Wallpaper &
#Xrandr &
/usr/lib/notify-osd/notify-osd &
#/usr/lib/mate-notification-daemon/mate-notification-daemon &
tint2 &

xrefresh
#xpad &
#/usr/bin/xfce4-clipman &
numlockx on &
parcellite &
xrefresh
#~/.local/bin/barcomplete.sh &
xcompmgr &
transmission-gtk -m &
#picom --experimental-backends --backend glx --xrender-sync-fence &

Cursor_Theme_Fix &
Battery_Check &

if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
      # if not found, launch a new one
      export $(dbus-launch)
      eval `dbus-launch --sh-syntax --exit-with-session openbox`
      echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
else
      exec openbox
fi
